#! /bin/sh

# with serial its easier to read the logs

echo "MULLE_HOSTNAME=\"${MULLE_HOSTNAME}\"" 2>&1

mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" extension show &&
mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" init -d exe -m mulle-objc/objc-developer executable &&
cd exe &&
(
   echo "Adding environment-host-travis-ci-prerelease file from MulleObjC/test" >&2 &&
   cd .mulle/etc/env &&
   curl -L -O "https://raw.githubusercontent.com/mulle-objc/MulleObjC/prerelease/test/.mulle/etc/env/environment-host-travis-ci-prerelease.sh" >&2
) &&
mulle-sde hostname &&
mulle-sde environment &&
mulle-sde craft --release &&
"./kitchen/Release/exe" &&
cd .. &&
mulle-sde -DMULLE_SDE_EXTENSION_BASE_PATH="${PWD}/src" init -d lib -m mulle-objc/objc-developer library &&
cd lib &&
(
   echo "Adding environment-host-travis-ci-prerelease file from MulleObjC/test" >&2 &&
   cd .mulle/etc/env &&
   curl -L -O "https://raw.githubusercontent.com/mulle-objc/MulleObjC/prerelease/test/.mulle/etc/env/environment-host-travis-ci-prerelease.sh" >&2
) &&
mulle-sde craft
