#! /usr/bin/env bash
#
#   Copyright (c) 2017 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#

#
# environment
#


usage()
{
   cat <<EOF >&2
usage:
   ${MULLE_EXECUTABLE} [options] <name> [dependencies]

   Name is the name of the library without prefix or
   extension and without "Standalone" suffix.
   Dependencies is the list of Objective-C dependencies
   of this library.

   Options:
      -n        : don't actually do anything
      -o <file> : write output to file
EOF
   exit 1
}


setup_bootstrap_environment()
{
   local libexec

   libexec="`mulle-bootstrap library-path 2> /dev/null | head -1`"
   if [ -z "${libexec}" ]
   then
      echo "mulle-bootstrap not installed or not in PATH: $PATH" >&2
      exit 1
   fi

   PATH="${libexec}:${PATH}"

   . mulle-bootstrap-logging.sh
   . mulle-bootstrap-functions.sh
   . mulle-bootstrap-local-environment.sh
}


#
# For each dependency, emit the necessary dependency on the loader
# except for MulleObjC
#
_dump_loader_dependencies()
{
   local depfile
   local depname

   local classid
   local categoryid

   classid="`mulle-objc-uniqueid MulleObjCLoader | tail -1`"
   while [ $# -ne 0 ]
   do
      depfile="${DEPENDENCIES}/include/$1/dependencies.inc"

      if [ ! -f "${depfile}" ]
      then
         fail "\"${depfile}\" not found, mulle-bootstrap first"
      fi

      depname="$1"
      case "${depname}" in
         MulleObjC)
            depname=""
         ;;
      esac

      if [ ! -z "${depname}" ]
      then
         categoryid="`mulle-objc-uniqueid "${depname}" | tail -1`"
         exekutor echo "      { @selector( MulleObjCLoader), \
@selector( ${depname}) },      // $classid,$categoryid"
      fi

      shift
   done
}


_combine_dependencies_inc()
{
   local depfile

   while [ $# -ne 0 ]
   do
      depfile="${DEPENDENCIES}/include/$1/dependencies.inc"

      if [ ! -f "${depfile}" ]
      then
         fail "\"${depfile}\" not found, mulle-bootstrap first"
      fi

      cat "${depfile}"

      shift
   done
}


_do_dump_dependencies()
{
   #
   # First get all classes and categories "below" OS for later removal
   # Then get all standalone classes, but remove Posix classes and
   # OS specifica. The remainder are osbase-dependencies
   #
   local tmpplus
   local tmpminus

   tmpplus="`mktemp "/tmp/plus-XXXXXX"`"
   tmpminus="`mktemp "/tmp/minus-XXXXXX"`"

   redirect_exekutor "${tmpminus}" _combine_dependencies_inc "$@" || fail "combine failed"
   redirect_exekutor "${tmpplus}" mulle-objc-list -d "${BUILDPATH}/${STANDALONE_LIB}" || fail "mulle-objc-list failed"

   #
   # remove inherited dependencies from standalone dependencies
   # also remove MulleObjCLoader class as dependency
   #
   if [ ! -z "`cat "${tmpminus}"`" ]
   then
      exekutor fgrep -x -v -f"${tmpminus}" "${tmpplus}"
   else
      cat "${tmpplus}"
   fi

   if [ "${OPTION_REMOVE_TMP}" = "YES" ]
   then
      rm "${tmpplus}" "${tmpminus}"
   else
      log_info "${tmpplus} and ${tmpminus} not removed"
   fi
}


_dump_dependencies()
{
   #
   # get path for mulle-objc-list
   #
   DEPENDENCIES="`mulle-bootstrap paths dependencies`"
   if [ -z "${DEPENDENCIES}" ]
   then
      fail "Could not get the dependencies path via mulle-boostrap paths"
   fi

   log_fluff "DEPENDENCIES : $PWD"

   _dump_loader_dependencies "$@" | sort | sort -u
   if [ ! -z "${STANDALONE_LIB}" ]
   then
      _do_dump_dependencies "$@" | sort | sort -u
   fi
}


dump_dependencies()
{
   log_fluff "PWD          : $PWD"
   log_fluff "ARGV         : $*"
   log_fluff "BUILDPATH    : ${BUILDPATH}"

   _dump_dependencies "$@" |
      fgrep -v '{ @selector( MulleObjCLoader), MULLE_OBJC_NO_CATEGORYID }'
}


#
# parameters are dependencies
#
main()
{
   setup_bootstrap_environment

   local BUILDPATH="${BUILDPATH:-.}"
   local OPTION_REMOVE_TMP="YES"
   local OUTPUT

   while [ $# -ne 0 ]
   do
      if bootstrap_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h|--help)
            usage
         ;;

         --no-remove)
            OPTION_REMOVE_TMP="NO"
         ;;

         -b|--build-path)
            [ $# -eq 1 ] && usage
            shift

            BUILDPATH="$1"
         ;;

         -n|--dry-run)
            MULLE_FLAG_EXECUTOR_DRY_RUN="YES"
         ;;

         -o|--output)
            [ $# -eq 1 ] && usage
            shift

            OUTPUT="$1"
         ;;

         -)
            break
         ;;

         -*)
            usage
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   [ "${MULLE_TRACE}" = "1848" ] && set -x

   NAME="$1"
   [ -z "${NAME}" ] && usage
   shift

   case "${NAME}" in
      ""|"-")
      ;;

      *)
         case "`uname -s`" in
            Darwin)
               STANDALONE_LIB="lib${NAME}Standalone.dylib"
            ;;

            MINGW*|Win*|WIN*)
              STANDALONE_LIB="${NAME}Standalone.dll" # assume
            ;;

            *)
              STANDALONE_LIB="lib${NAME}Standalone.so"
            ;;
         esac
      ;;
   esac

   eval `mulle-bootstrap paths path` || fail "mulle-bootstrap not found"

   if [ -z "`command -v mulle-objc-list`" ]
   then
      fail "mulle-objc-list not found in PATH"
   fi

   #
   # could build it dynamically --
   #
   if [ ! -z "${STANDALONE_LIB}" -a  ! -f "${BUILDPATH}/${STANDALONE_LIB}" ]
   then
      fail "${BUILDPATH}/${STANDALONE_LIB} not found. \
mulle-build first or specify build directory with -b"
   fi

   local result

   result="`dump_dependencies "$@"`"
   if [ -z "${OUTPUT}" ]
   then
      exekutor echo "$result"
   else
      local previous

      if [ -f "${OUTPUT}" ]
      then
         local before

         before="`cat "${OUTPUT}"`"
         if [ "${result}" = "${before}" ]
         then
            log_verbose "Contents \"dependencies.inc\" already up to date"
            return 0
         fi
      fi
      redirect_exekutor "${OUTPUT}" echo "${result}"
   fi
}


# sometimes passed in
if [ -z "${MULLE_EXECUTABLE}" ]
then
   MULLE_EXECUTABLE="`basename -- "$0"`"
   MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE}"
fi

MULLE_ARGUMENTS="$@"
MULLE_EXECUTABLE_PID="$$"
export MULLE_EXECUTABLE_PID

main "$@"
