/* DO:    #import this files in public headers

   DONT:  #import this file in private headers
          #import this files in directly in sources
          #include this file anywhere
*/

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/

/*
   Get C includes first
 */
#import "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#import "_<|PROJECT_NAME|>-import.h"

/* You can add some more import statements here */

