name: DockerfileCI

on: [push]


jobs:
  build:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v2
       if: ${{ ! env.ACT }}

     - name: Build Docker image
       if: ${{ ! env.ACT }}
       run: docker build .
 
