name: CI

on: [push]

env:
  BUILD_TYPE: release
  OTHER_PROJECTS: "mulle-objc/mulle-objc-developer;
mulle-c/mulle-c-developer;"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]

    steps:
    - name: Set MULLE_HOSTNAME
      run: echo "MULLE_HOSTNAME=ci-${GITHUB_REF##*/}" >> $GITHUB_ENV

    - uses: actions/checkout@v2

    - uses: mulle-sde/github-ci@v1

    - uses: mulle-objc/github-ci@v1

    - name: Add to path
      run:  echo "$HOME/bin" >> $GITHUB_PATH

    - name: Dump Environment
      run:  env | sort

    - name: Mulle-SDE Excecutable
      run: |
        mulle-sde init -m objc-developer -d /tmp/executable executable &&
        mulle-sde -d /tmp/executable craft

    - name: Mulle-SDE Library
      run: |
        mulle-sde init -m objc-developer -d /tmp/library library &&
        mulle-sde -d /tmp/library craft
